package behavioralpatterns.chainofresponsabilitypattern.concretehandler

import behavioralpatterns.chainofresponsabilitypattern.concretehandler.base.DollarDispenser

class Dollar10Dispenser : DollarDispenser(10)