package behavioralpatterns.chainofresponsabilitypattern.concretehandler

import behavioralpatterns.chainofresponsabilitypattern.concretehandler.base.DollarDispenser

class Dollar20Dispenser : DollarDispenser(20)