package behavioralpatterns.chainofresponsabilitypattern.concretehandler

import behavioralpatterns.chainofresponsabilitypattern.concretehandler.base.DollarDispenser

class Dollar50Dispenser : DollarDispenser(50)